"""ChequeMate AI Review and OCR Verification Report - a SEPARATE, additive
report version. The original reports/chequemate_report.html is never
touched by this module (still generated by report.regenerate_report(),
unchanged) - this writes a second file,
reports/chequemate_verification_report.html, so the original stays
available for rollback/comparison at all times, per the task's explicit
"create a new report version, do not silently change the current one"
requirement.

Reuses report.py's JSON-embedding helper (`_json_for_script`) and data
access functions (`load_records`, `load_reviews`) rather than duplicating
them - this module owns only what's genuinely new: the verification-
specific template and the summary/field-verification rendering logic.

Every record already stored in cheques.json (via report.create_report_record)
is privacy-safe by construction - no MICR, no account numbers, no signature
images, no raw Azure response ever gets persisted there (see report.py's
"privacy boundary" design). This report renders directly from that same
already-safe data plus the new `ocr_verifications` field, so it inherits
those guarantees rather than needing to re-implement them.
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path

from . import report as _report
from .validate import RULE_SET_VERSION

VERIFICATION_SCHEMA_VERSION = "1.0"
TROCR_DEFAULT_MODEL_ID = "microsoft/trocr-base-handwritten"

HTML_VERIFICATION_REPORT = _report.REPORTS_DIR / "chequemate_verification_report.html"

REVIEWER_NOTICE = (
    "This report assists human review. OCR verification does not "
    "constitute autonomous approval. Differences between extraction "
    "engines must be checked against the cheque image."
)

_FIELD_LABELS = {
    "payee": "Payee",
    "amount_words": "Legal amount (amount in words)",
    "memo": "Memo / roll number",
}

_COMPARISON_GUIDANCE = {
    "AGREE_EXACT": ("Agreement observed", "ok",
                    "Document Intelligence and TrOCR produced identical text. "
                    "No independent action needed for this field."),
    "AGREE_NORMALIZED": ("Agreement observed", "ok",
                         "Both engines agree once case/whitespace differences "
                         "are set aside. No independent action needed."),
    "AGREE_ALLOWLIST": ("Agreement observed (allowlist)", "ok",
                       "Both engines independently matched the expected payee "
                       "despite differing spelling - the spelling difference "
                       "is shown below, not hidden."),
    "DISAGREE": ("Manual review required", "bad",
                "Document Intelligence and TrOCR produced different readings. "
                "Neither result has been automatically substituted - check "
                "both values against the source cheque image."),
    "DI_ONLY": ("Secondary verification unavailable", "warn",
               "TrOCR did not run for this field. Document Intelligence's "
               "value stands unchanged; this is expected, not an error."),
    "TROCR_ONLY": ("Manual review required - unverified suggestion", "bad",
                  "Document Intelligence produced no usable value. TrOCR's "
                  "reading is shown as a secondary suggestion only and has "
                  "NOT been promoted to an authoritative value."),
    "CROP_REJECTED": ("Secondary verification unavailable", "warn",
                      "The candidate region for this field failed crop "
                      "validation, so TrOCR was never run. Document "
                      "Intelligence's value stands unchanged."),
    "TROCR_NOT_RUN": ("Secondary verification unavailable", "warn",
                      "No usable field region was available for TrOCR "
                      "(missing/unreadable polygon). Document Intelligence's "
                      "value stands unchanged."),
    "TROCR_FAILED": ("Secondary verification unavailable", "warn",
                     "The local TrOCR model failed to run for this field. "
                     "Document Intelligence's value stands unchanged."),
    "BOTH_UNDETERMINED": ("Manual review required - undetermined", "bad",
                         "Neither engine produced a usable value for this "
                         "field. Nothing has been guessed or fabricated."),
}


def _esc(value) -> str:
    if value is None:
        return "—"
    return html.escape(str(value), quote=True)


def _score_display(score, score_type: str) -> str:
    if score_type != "raw_generation_evidence" or score is None:
        return "Not calibrated"
    return f"{score:.3f} (raw generation evidence - not a calibrated confidence)"


def _field_card_html(field_name: str, fv: dict) -> str:
    primary = fv.get("primary", {})
    crop = fv.get("crop", {})
    secondary = fv.get("secondary", {})
    comparison = fv.get("comparison", {})

    status = comparison.get("status", "TROCR_NOT_RUN")
    label, tone, guidance = _COMPARISON_GUIDANCE.get(
        status, ("Unknown status", "warn", "Unrecognized comparison status."))

    reason_codes = comparison.get("reason_codes") or []
    reason_html = "".join(f'<span class="reason-chip">{_esc(rc)}</span>'
                          for rc in reason_codes)

    bbox = crop.get("pixel_bbox")
    bbox_text = (f"({bbox[0]}, {bbox[1]}) - ({bbox[2]}, {bbox[3]}) px"
                if bbox else "n/a")
    crop_reasons = "; ".join(crop.get("validation_reasons") or []) or "n/a"
    image_ref = crop.get("image_reference")

    return f"""
<div class="field-card tone-{tone}">
  <div class="field-card-head">
    <span class="field-name">{_esc(_FIELD_LABELS.get(field_name, field_name))}</span>
    <span class="status-pill tone-{tone}">{_esc(label)}</span>
  </div>
  <div class="field-guidance">{_esc(guidance)}</div>
  {f'<div class="reason-chips">{reason_html}</div>' if reason_html else ''}
  <div class="observation-grid">
    <div class="observation">
      <h5>Document Intelligence (primary)</h5>
      <div class="obs-row"><span class="obs-label">Value</span>
        <span class="obs-value">{_esc(primary.get('raw_value'))}</span></div>
      <div class="obs-row"><span class="obs-label">Confidence</span>
        <span class="obs-value">{_esc(primary.get('confidence'))}</span></div>
      <div class="obs-row"><span class="obs-label">Model</span>
        <span class="obs-value">{_esc(primary.get('model_id'))}</span></div>
    </div>
    <div class="observation">
      <h5>TrOCR (secondary observation)</h5>
      <div class="obs-row"><span class="obs-label">Value</span>
        <span class="obs-value">{_esc(secondary.get('raw_value'))}</span></div>
      <div class="obs-row"><span class="obs-label">Status</span>
        <span class="obs-value">{_esc(secondary.get('status'))}</span></div>
      <div class="obs-row"><span class="obs-label">Score</span>
        <span class="obs-value">{_esc(_score_display(secondary.get('score'), secondary.get('score_type', 'unavailable')))}</span></div>
      <div class="obs-row"><span class="obs-label">Model</span>
        <span class="obs-value">{_esc(secondary.get('model_id'))} / {_esc(secondary.get('model_version'))}</span></div>
      <div class="obs-row"><span class="obs-label">Preprocessing</span>
        <span class="obs-value">{_esc(secondary.get('preprocessing_variant'))}</span></div>
    </div>
  </div>
  <details class="crop-evidence">
    <summary>Crop evidence &amp; audit detail</summary>
    <div class="obs-row"><span class="obs-label">Crop status</span>
      <span class="obs-value">{_esc(crop.get('status'))}</span></div>
    <div class="obs-row"><span class="obs-label">Pixel bounding box</span>
      <span class="obs-value">{_esc(bbox_text)}</span></div>
    <div class="obs-row"><span class="obs-label">Validation notes</span>
      <span class="obs-value">{_esc(crop_reasons)}</span></div>
    <div class="obs-row"><span class="obs-label">Debug crop reference</span>
      <span class="obs-value">{_esc(image_ref) if image_ref else 'not retained (debug crop retention is off by default)'}</span></div>
    <div class="obs-row"><span class="obs-label">Similarity</span>
      <span class="obs-value">{_esc(comparison.get('similarity'))}</span></div>
    <div class="obs-row"><span class="obs-label">Selected display value</span>
      <span class="obs-value">{_esc(comparison.get('selected_display_value'))} (source: {_esc(comparison.get('selection_source'))})</span></div>
  </details>
  {'<div class="disagreement-warning">Manual verification required: Document Intelligence and TrOCR produced different readings for this field. Neither result has been automatically substituted.</div>' if status == 'DISAGREE' else ''}
</div>"""


def _rule_row_html(rule_id: str, rule: dict) -> str:
    status = rule.get("status", "UNABLE")
    tone = {"PASS": "ok", "FAIL": "bad", "UNABLE": "warn"}.get(status, "warn")
    return f"""
<div class="rule-row tone-{tone}">
  <span class="rule-id">{_esc(rule_id)}</span>
  <span class="status-pill tone-{tone}">{_esc(status)}</span>
  <span class="rule-message">{_esc(rule.get('message'))}</span>
</div>"""


def _record_section_html(record: dict) -> str:
    verdict = record.get("verdict", "REVIEW")
    verdict_tone = {"VALID": "ok", "REVIEW": "warn", "INVALID": "bad"}.get(verdict, "warn")
    ocr = record.get("ocr_verifications") or {}
    rules = record.get("rules") or {}

    ocr_disagreements = sum(1 for fv in ocr.values()
                            if fv.get("comparison", {}).get("status") == "DISAGREE")
    not_secondarily_verified = sum(
        1 for fv in ocr.values()
        if fv.get("comparison", {}).get("status") in
        ("DI_ONLY", "CROP_REJECTED", "TROCR_NOT_RUN", "TROCR_FAILED"))
    manual_review_fields = sum(
        1 for fv in ocr.values()
        if fv.get("comparison", {}).get("manual_review_required"))

    field_cards = "".join(_field_card_html(name, fv) for name, fv in ocr.items())
    rule_rows = "".join(_rule_row_html(rid, r) for rid, r in rules.items())

    ocr_block = (field_cards if field_cards else
                '<div class="empty-note">TrOCR verification was not run for this '
                'record (feature disabled, or the cheque predates this feature).</div>')

    return f"""
<section class="record-card tone-{verdict_tone}" id="record-{_esc(record.get('record_id'))}">
  <div class="record-head">
    <div>
      <span class="record-id">{_esc(record.get('record_id'))}</span>
      <span class="source-file">{_esc(record.get('source_file'))}</span>
    </div>
    <div class="record-head-right">
      <span class="status-pill tone-{verdict_tone}">{_esc(verdict)}</span>
      <span class="manual-review-flag">{'Manual review required' if manual_review_fields or verdict != 'VALID' else 'No additional OCR review flags'}</span>
    </div>
  </div>
  <div class="record-meta">
    Processed {_esc(record.get('processed_time'))} &middot;
    Ruleset {_esc(record.get('ruleset_version'))} &middot;
    OCR disagreements: {ocr_disagreements} &middot;
    Fields not secondarily verified: {not_secondarily_verified}
  </div>
  <h4 class="section-heading">Field verification (Document Intelligence vs. TrOCR)</h4>
  <div class="field-cards">{ocr_block}</div>
  <h4 class="section-heading">Deterministic business rules (unchanged, all still executed)</h4>
  <div class="rule-rows">{rule_rows}</div>
</section>"""


def generate_verification_html(records: list[dict], reviews: list[dict] | None = None,
                               *, trocr_model_id: str = TROCR_DEFAULT_MODEL_ID,
                               trocr_model_revision: str | None = None,
                               di_model_id: str = _report.MODEL_ID) -> str:
    reviews = reviews or []
    total = len(records)
    verified_records = [r for r in records if r.get("ocr_verifications")]
    total_disagreements = sum(
        1 for r in records for fv in (r.get("ocr_verifications") or {}).values()
        if fv.get("comparison", {}).get("status") == "DISAGREE")
    total_not_verified_fields = sum(
        1 for r in records for fv in (r.get("ocr_verifications") or {}).values()
        if fv.get("comparison", {}).get("status") in
        ("DI_ONLY", "CROP_REJECTED", "TROCR_NOT_RUN", "TROCR_FAILED"))
    rule_failures = sum(1 for r in records for rule in (r.get("rules") or {}).values()
                        if rule.get("status") == "FAIL")
    rule_undetermined = sum(1 for r in records for rule in (r.get("rules") or {}).values()
                            if rule.get("status") == "UNABLE")
    manual_review_needed = sum(1 for r in records if r.get("verdict") != "VALID") or \
        sum(1 for r in records for fv in (r.get("ocr_verifications") or {}).values()
           if fv.get("comparison", {}).get("manual_review_required"))

    generated = datetime.now().astimezone().isoformat(timespec="seconds")
    records_sorted = sorted(records, key=lambda r: r.get("processed_time", ""), reverse=True)
    record_sections = "".join(_record_section_html(r) for r in records_sorted)

    return _TEMPLATE.format(
        css=_CSS,
        generated=html.escape(generated),
        total=total,
        verified_count=len(verified_records),
        report_schema_version=VERIFICATION_SCHEMA_VERSION,
        ruleset_version=html.escape(RULE_SET_VERSION),
        di_model_id=html.escape(di_model_id),
        trocr_model_id=html.escape(trocr_model_id),
        trocr_model_revision=html.escape(trocr_model_revision or "unpinned"),
        reviewer_notice=html.escape(REVIEWER_NOTICE),
        rule_failures=rule_failures,
        rule_undetermined=rule_undetermined,
        total_disagreements=total_disagreements,
        total_not_verified_fields=total_not_verified_fields,
        manual_review_needed=manual_review_needed,
        record_sections=record_sections or
        '<div class="empty-note">No cheque records yet.</div>',
    )


def regenerate_verification_report(*, trocr_model_id: str = TROCR_DEFAULT_MODEL_ID,
                                   trocr_model_revision: str | None = None) -> Path:
    """Rebuild the verification report in full from the current JSON records -
    same "always fully rebuilt, never patched" policy as report.py's own
    regenerate_report(). Safe to call even when no record has ocr_verifications
    data yet (renders an honest "not run" state per record instead of
    erroring)."""
    records = _report.load_records()
    reviews = _report.load_reviews()
    html_text = generate_verification_html(
        records, reviews, trocr_model_id=trocr_model_id,
        trocr_model_revision=trocr_model_revision)
    _report._atomic_write_text(HTML_VERIFICATION_REPORT, html_text)
    return HTML_VERIFICATION_REPORT


_CSS = """
:root{
  color-scheme: dark;
  --bg-a:#0b0f1e; --bg-b:#111827; --bg-c:#0d1b1a;
  --glass:rgba(255,255,255,0.055); --glass-strong:rgba(255,255,255,0.09);
  --glass-border:rgba(255,255,255,0.14);
  --text-primary:#f3f5f9; --text-secondary:#aab2c5; --muted:#707c93;
  --brand-a:#a78bfa; --brand-b:#22d3ee;
  --ok:#34d399; --ok-bg:rgba(52,211,153,0.16);
  --bad:#fb7185; --bad-bg:rgba(251,113,133,0.16);
  --warn:#fbbf24; --warn-bg:rgba(251,191,36,0.16);
}
*{box-sizing:border-box}
body{
  margin:0; font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  background:radial-gradient(1200px 600px at 10% -10%, var(--bg-c), transparent),
             radial-gradient(1200px 800px at 110% 10%, var(--bg-b), transparent),
             var(--bg-a);
  color:var(--text-primary); line-height:1.45;
}
.wrap{max-width:1100px; margin:0 auto; padding:28px 20px 80px}
header.top{
  background:var(--glass-strong); border:1px solid var(--glass-border);
  border-radius:16px; padding:22px 26px; margin-bottom:18px;
}
header.top h1{margin:0 0 6px; font-size:1.5rem}
.meta-line{color:var(--text-secondary); font-size:0.88rem; margin:2px 0}
.notice{
  background:var(--warn-bg); border:1px solid var(--warn); color:var(--warn);
  border-radius:12px; padding:14px 18px; margin:16px 0; font-size:0.92rem;
}
.summary-grid{
  display:grid; grid-template-columns:repeat(5,1fr); gap:12px; margin:18px 0 26px;
}
@media (max-width:900px){.summary-grid{grid-template-columns:repeat(2,1fr)}}
.tile{
  background:var(--glass); border:1px solid var(--glass-border); border-radius:12px;
  padding:14px 16px;
}
.tile .value{font-size:1.6rem; font-weight:700}
.tile .label{color:var(--text-secondary); font-size:0.78rem; text-transform:uppercase; letter-spacing:.04em}
.record-card{
  background:var(--glass); border:1px solid var(--glass-border); border-radius:14px;
  padding:18px 20px; margin-bottom:16px;
}
.record-card.tone-bad{border-color:rgba(251,113,133,0.5)}
.record-card.tone-warn{border-color:rgba(251,191,36,0.5)}
.record-head{display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:8px}
.record-id{font-weight:700; margin-right:10px}
.source-file{color:var(--text-secondary); font-size:0.85rem}
.record-head-right{display:flex; align-items:center; gap:10px}
.manual-review-flag{font-size:0.8rem; color:var(--text-secondary)}
.record-meta{color:var(--text-secondary); font-size:0.82rem; margin:8px 0 14px}
.section-heading{font-size:0.95rem; margin:16px 0 10px; color:var(--text-secondary)}
.status-pill{
  display:inline-block; padding:3px 10px; border-radius:999px; font-size:0.76rem; font-weight:600;
}
.status-pill.tone-ok{background:var(--ok-bg); color:var(--ok)}
.status-pill.tone-bad{background:var(--bad-bg); color:var(--bad)}
.status-pill.tone-warn{background:var(--warn-bg); color:var(--warn)}
.field-cards{display:grid; gap:12px}
.field-card{
  background:rgba(255,255,255,0.03); border:1px solid var(--glass-border);
  border-radius:12px; padding:14px 16px;
}
.field-card.tone-bad{border-color:rgba(251,113,133,0.45)}
.field-card-head{display:flex; justify-content:space-between; align-items:center; margin-bottom:6px}
.field-name{font-weight:600}
.field-guidance{color:var(--text-secondary); font-size:0.85rem; margin-bottom:8px}
.reason-chips{margin:6px 0}
.reason-chip{
  display:inline-block; background:rgba(255,255,255,0.08); border-radius:6px;
  padding:2px 8px; font-size:0.72rem; margin-right:6px; color:var(--text-secondary);
  font-family:ui-monospace,monospace;
}
.observation-grid{display:grid; grid-template-columns:1fr 1fr; gap:14px; margin:10px 0}
@media (max-width:700px){.observation-grid{grid-template-columns:1fr}}
.observation h5{margin:0 0 6px; font-size:0.78rem; text-transform:uppercase; color:var(--text-secondary); letter-spacing:.04em}
.obs-row{display:flex; justify-content:space-between; gap:10px; font-size:0.85rem; padding:2px 0; border-bottom:1px dashed rgba(255,255,255,0.06)}
.obs-label{color:var(--text-secondary)}
.obs-value{text-align:right; word-break:break-word; max-width:65%}
.crop-evidence{margin-top:8px; font-size:0.85rem}
.crop-evidence summary{cursor:pointer; color:var(--brand-b)}
.disagreement-warning{
  margin-top:10px; background:var(--bad-bg); color:var(--bad); border-radius:8px;
  padding:8px 12px; font-size:0.82rem; font-weight:600;
}
.rule-rows{display:grid; gap:6px}
.rule-row{
  display:grid; grid-template-columns:120px 90px 1fr; gap:10px; align-items:center;
  background:rgba(255,255,255,0.03); border-radius:8px; padding:8px 12px; font-size:0.85rem;
}
.rule-id{font-family:ui-monospace,monospace; color:var(--text-secondary)}
.rule-message{color:var(--text-secondary); word-break:break-word}
.empty-note{color:var(--muted); font-size:0.85rem; font-style:italic; padding:10px 0}
footer.bottom{color:var(--muted); font-size:0.8rem; text-align:center; margin-top:30px}
"""

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ChequeMate AI Review and OCR Verification Report</title>
<style>{css}</style>
</head>
<body>
<div class="wrap">
<header class="top">
  <h1>ChequeMate AI Review and OCR Verification Report</h1>
  <div class="meta-line">Generated {generated}</div>
  <div class="meta-line">Report schema {report_schema_version} &middot; Ruleset {ruleset_version}</div>
  <div class="meta-line">Document Intelligence model: {di_model_id}</div>
  <div class="meta-line">TrOCR model: {trocr_model_id} (revision: {trocr_model_revision})</div>
</header>

<div class="notice">{reviewer_notice}</div>

<div class="summary-grid">
  <div class="tile"><div class="value">{total}</div><div class="label">Cheques in report</div></div>
  <div class="tile"><div class="value">{rule_failures}</div><div class="label">Rule failures</div></div>
  <div class="tile"><div class="value">{rule_undetermined}</div><div class="label">Rules undetermined</div></div>
  <div class="tile"><div class="value">{total_disagreements}</div><div class="label">OCR field disagreements</div></div>
  <div class="tile"><div class="value">{total_not_verified_fields}</div><div class="label">Fields not secondarily verified</div></div>
</div>

<div class="meta-line" style="margin-bottom:18px">
  {verified_count} of {total} cheques have at least one field with TrOCR secondary
  verification data. No aggregate confidence score is computed anywhere in this
  report - each field's evidence is shown individually below.
</div>

{record_sections}

<footer class="bottom">
  ChequeMate AI Review and OCR Verification Report &middot; v1 remains reviewer
  assist and does not autonomously approve cheques.
</footer>
</div>
</body>
</html>"""
